---
 - name: Parcha un conjunto de servidores linux
   # A quienes se le va a operar el parchado
   hosts: all
   tasks:
    - name: Dame un mensaje 
      ansible.builtin.debug: 
        msg: "Bienvenido al mundo Ansible"

    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
